### ISSUE TITLE
Implement Feed Foward Layer

### ISSUE THREAD

**Issue by BrunaKLacerda** [B-Srujana/IS640-GPT-Project#14]
Updating the model to include Feed Forward Layers enhances its capability by processing each token independently after interactions with other tokens in the sequence. While attention mechanisms enable tokens to 'communicate' and exchange information, Feed Forward Layers allow each token to refine and deepen its understanding of the aggregated context. This additional step adds depth and complexity to the model, ensuring that tokens not only gather information from others but also process and transform it effectively for downstream tasks.

**Comment by SrujanaBotcha** [comment]
This issue has been fixed and updated.
